application: traclogs
version: 20150118-01
runtime: go
api_version: go1

handlers:

- url: /_ah/queue/go/delay
  script: _go_app
  login: admin

- url: /mng/
  static_files: static/index.html
  upload: static/index.html

- url: /mng/(.*)
  static_files: static/\1
  upload: static/.*

- url: /.*
  script: _go_app
